services:
  postgres:
    image: postgres:latest
    container_name: trabalho_bd
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - trabalho_bd_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/1-esquema.sql
      - ./db/data.sql:/docker-entrypoint-initdb.d/2-dados.sql
    networks:
      - app_network

  python_app:
    build: ./Python
    container_name: python_app
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    volumes:
      - ./Python:/app
    command: python /app/app/sistema.py
    networks:
      - app_network

volumes:
  trabalho_bd_data:
    driver: local

networks:
  app_network:
    driver: bridge