# Generated by Django 5.1.4 on 2024-12-11 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='website_usuario',
        ),
    ]
