# Generated by Django 5.1.4 on 2024-12-12 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_alergia_table_alter_atendente_table_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alergia',
            new_name='Alergias',
        ),
        migrations.RenameModel(
            old_name='Atendente',
            new_name='Atendentes',
        ),
        migrations.RenameModel(
            old_name='Consulta',
            new_name='Consultas',
        ),
        migrations.RenameModel(
            old_name='Medico',
            new_name='Medicos',
        ),
        migrations.RenameModel(
            old_name='Paciente',
            new_name='Pacientes',
        ),
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Usuarios',
        ),
        migrations.AlterModelTable(
            name='alergias',
            table=None,
        ),
        migrations.AlterModelTable(
            name='atendentes',
            table=None,
        ),
        migrations.AlterModelTable(
            name='medicos',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pacientes',
            table=None,
        ),
        migrations.AlterModelTable(
            name='usuarios',
            table=None,
        ),
    ]
