# Generated by Django 5.1.4 on 2024-12-12 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_alergia_alergias_rename_atendente_atendentes_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alergias',
            new_name='Alergia',
        ),
        migrations.RenameModel(
            old_name='Atendentes',
            new_name='Atendente',
        ),
        migrations.RenameModel(
            old_name='Consultas',
            new_name='Consulta',
        ),
        migrations.RenameModel(
            old_name='Medicos',
            new_name='Medico',
        ),
        migrations.RenameModel(
            old_name='Pacientes',
            new_name='Paciente',
        ),
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
        migrations.AlterModelTable(
            name='alergia',
            table='alergias',
        ),
        migrations.AlterModelTable(
            name='atendente',
            table='atendentes',
        ),
        migrations.AlterModelTable(
            name='consulta',
            table='consultas',
        ),
        migrations.AlterModelTable(
            name='medico',
            table='medicos',
        ),
        migrations.AlterModelTable(
            name='paciente',
            table='pacientes',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
    ]
