# Generated by Django 5.1.4 on 2024-12-17 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_alergia_alergia_alter_alergia_paciente_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consulta',
            unique_together={('medico', 'atendente', 'data_consulta')},
        ),
    ]
